# Generated by Django 3.2 on 2021-04-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('discriminator', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('locale', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField()),
            ],
        ),
    ]
