# Generated by Django 3.2 on 2021-04-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210415_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='UlalaMapArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ulalaboss',
            name='area',
        ),
        migrations.AddField(
            model_name='ulalaboss',
            name='map_area',
            field=models.ManyToManyField(to='main_app.UlalaMapArea'),
        ),
    ]
