# Generated by Django 3.2 on 2021-04-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_discorduser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulalaskill',
            name='energy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ulalaskill',
            name='energy_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='playersetup',
            name='boss_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='main_app.bosssetup'),
        ),
        migrations.AlterField(
            model_name='ulalaskill',
            name='img_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ulalatoy',
            name='img_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
