# Generated by Django 3.2 on 2021-04-28 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_ulalatoy_related_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playersetup',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='playersetup',
            name='toys',
        ),
        migrations.AddField(
            model_name='playersetup',
            name='skill1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='main_app.ulalaskill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playersetup',
            name='skill2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='main_app.ulalaskill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playersetup',
            name='skill3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='main_app.ulalaskill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playersetup',
            name='skill4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='main_app.ulalaskill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playersetup',
            name='toy1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='main_app.ulalatoy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playersetup',
            name='toy2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='main_app.ulalatoy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playersetup',
            name='toy3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='main_app.ulalatoy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playersetup',
            name='toy4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='main_app.ulalatoy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bosssetup',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bosssetup',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
