# Generated by Django 3.2 on 2021-05-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210501_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulalatoydescription',
            name='awakening_effect',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ulalatoydescription',
            name='six_piece_effect',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ulalatoydescription',
            name='three_piece_effect',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
