# Generated by Django 3.2 on 2021-05-01 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_ulalatoydescription_toy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulalatoydescription',
            name='toy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='main_app.ulalatoy'),
        ),
    ]
