# Generated by Django 3.2 on 2021-05-08 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_ulalaclass_display_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='avatar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savetouser',
            name='boss_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='main_app.bosssetup'),
        ),
    ]
