# Generated by Django 3.2 on 2021-05-09 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210508_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='boss_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.bosssetup'),
        ),
    ]
