# Generated by Django 3.2 on 2021-04-18 15:54

from django.db import migrations
import main_app.managers


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210416_0508'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', main_app.managers.DiscordUserOAuth2Manager()),
            ],
        ),
    ]
