# Generated by Django 3.2 on 2021-04-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210421_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulalatoy',
            name='related_class',
            field=models.ManyToManyField(related_name='toy_list', to='main_app.UlalaClass'),
        ),
    ]
