# Generated by Django 3.2 on 2021-04-29 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210428_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bosssetup',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
