# Generated by Django 3.2 on 2021-04-29 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_bosssetup_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playersetup',
            name='boss_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_setup', to='main_app.bosssetup'),
        ),
    ]
