# Generated by Django 3.2 on 2021-05-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210429_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ulalatoy',
            name='description',
        ),
        migrations.AddField(
            model_name='ulalatoy',
            name='not_allowed_with',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UlalaToyDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toy_description', to='main_app.ulalatoy')),
            ],
        ),
    ]
